### PR TITLE
feat: add documentation for functions in index and util files

### LINKED ISSUE #56: Add documentation for each function
None of the functions used in the project have documentation. The functions need to be documented so that it is easier for users to understand how the code is working.

[Inline Documentation Standard](https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript/) will be a good starting point on how to write documentation.

### PR DESCRIPTION
**Pull request by vickywane**
The aim of this PR is to create function documentation using the JsDocs format for functions in the index and utils files. 

This PR will close #56

### CODE REVIEW

**Review by Delta456 — COMMENTED** [review]
Hi @vickywane! Thanks for opening PR. We appreciate your contribution. I have a few points which will make your PR even better

- Do not elaborate too much on private functions
- Functions documentation in general should be short and easy to understand
- Examples are not needed for private functions.

**Comment by vickywane** [comment]
Hi @Delta456 

Thank you for the comment on this. 

I will adjust my changes and request another review.

**Comment by vickywane** [comment]
Hi @Delta456 I've reduced the elaborations on the function documentations and removed the examples for the private functions within the `util.js` file. 

Looking forward to your next feedback.

**Review by harsha509 — APPROVED** [review]
Thank you @vickywane !

**Comment by vickywane** [comment]
You're welcome @harsha509 @Delta456  .   

Looking forward to the merge 🫡!

**Pull request merged**
