### PR TITLE
Updated the versions of dependencies

### PR DESCRIPTION
**Pull request by parthib2004**
I have updated the versions of the dependencies. Please check it! Thank you!

### CODE REVIEW

**Comment by harsha509** [comment]
Hi @parthib2004,

Thank you for the PR!

Generally, we update dependencies in the `package.json`, and the lock file is generated automatically. However, this PR only contains the lock file, and the corresponding `package.json` update seems to be missing.

Could you please include the package.json changes as well?

Thanks,
Sri

**Comment by harsha509** [comment]
Hello @parthib2004,

Thank you for your PR. Please note that the PR has been replaced with the merged [PR #62](https://github.com/LambdaTest/testcafe-browser-provider-lambdatest/pull/62).

We appreciate your efforts, and I encourage you to pick up another issue for contribution.

Thank you,
Sri

**Comment by subhramit** [comment]
> Hello @parthib2004,
> 
> Thank you for your PR. Please note that the PR has been replaced with the merged [PR #62](https://github.com/LambdaTest/testcafe-browser-provider-lambdatest/pull/62).
> 
> We appreciate your efforts, and I encourage you to pick up another issue for contribution.
> 
> Thank you, Sri

Hello Sir, in #62, I only updated Babel and ESLint as they were required in the context of my PR. The other dependency updates will still be relevant.

**Comment by harsha509** [comment]
HI @parthib2004 ,

I see the lock file update in here, could you please let me know if we're missing `package.json`.

**Pull request closed without merging**
