### PR TITLE
Prettify & Lint files

### PR DESCRIPTION
**Pull request by subhramit**
Closes https://github.com/LambdaTest/testcafe-browser-provider-lambdatest/issues/54
- Ran Prettier and ESLint. In case of style conflicts, preferred the former

### CODE REVIEW

**Comment by subhramit** [comment]
@navin772 @Delta456 Kindly take a look and let me know if anything needs to be reverted.

**Comment by subhramit** [comment]
Apologies for force-pushing. Had mistakenly used my other github handle for committing changes so had to reset the git history.

**Comment by subhramit** [comment]
@navin772 Navin, can you review this when you have time?

**Comment by harsha509** [comment]
Hi @subhramit,

The PR looks great!

Could you please also include the dependencies by merging the `package.json` and lock file? This way, I’ll have a complete working solution.

Thanks,
Sri

**Comment by subhramit** [comment]
> Hi @subhramit,
> 
> The PR looks great!
> 
> Could you please also include the dependencies by merging the `package.json` and lock file? This way, I’ll have a complete working solution.
> 
> Thanks, Sri

Done.

**Comment by subhramit** [comment]
@harsha509 Sri, is this alright?

**Review by harsha509 — APPROVED** [review]
Thank you @subhramit !

**Comment by Delta456** [comment]
@subhramit Hi, looks like your PR doesn't pass the actions. Can you take a look please.

**Comment by subhramit** [comment]
> @subhramit Hi, looks like your PR doesn't pass the actions. Can you take a look please.
> 
> https://github.com/LambdaTest/testcafe-browser-provider-lambdatest/actions/runs/11208379828/job/31151960827

Those warnings are from ESLint, which I superseded by Prettier when there were conflicts (as in the places I've worked, prettier used to be the norm).
Do you want me to override with ESLint's changes instead?

**Comment by Delta456** [comment]
> > @subhramit Hi, looks like your PR doesn't pass the actions. Can you take a look please.
> > 
> > https://github.com/LambdaTest/testcafe-browser-provider-lambdatest/actions/runs/11208379828/job/31151960827
> 
> Those warnings are from ESLint, which I superseded by Prettier when there were conflicts (as in the places I've worked, prettier used to be the norm).
> Do you want me to override with ESLint's changes instead?

Yes, please do. We need to make the CI green.

**Comment by subhramit** [comment]
@Delta456 Sorry for the delay.
https://github.com/LambdaTest/testcafe-browser-provider-lambdatest/pull/64

**Pull request merged**
